import { GoogleGenAI, Type } from "@google/genai";
import { StoryboardFrame } from "../types";

async function getAI() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please add it to your secrets.');
  }
  return new GoogleGenAI({ apiKey });
}

export async function parseScript(script: string): Promise<{ title: string; frames: Partial<StoryboardFrame>[] }> {
  const ai = await getAI();
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: script,
    config: {
      systemInstruction: `You are a professional storyboard artist and script supervisor. 
      Analyze the provided script and break it down into a sequence of key visual frames for a storyboard.
      For each frame, provide:
      1. description: What is happening visually in the scene.
      2. imagePrompt: A detailed, cinematic prompt for an AI image generator (including style, lighting, camera angle). Target a cinematic movie style.
      3. dialog: Any dialogue or key sound cues associated with the frame.
      Keep the number of frames between 4 and 10 for a standard script upload unless it's very short.
      Return the result as a JSON object with a 'title' for the sequence and an array of 'frames'.`,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          frames: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                sceneNumber: { type: Type.INTEGER },
                description: { type: Type.STRING },
                imagePrompt: { type: Type.STRING },
                dialog: { type: Type.STRING },
              },
              required: ["sceneNumber", "description", "imagePrompt"],
            },
          },
        },
        required: ["title", "frames"],
      },
    },
  });

  const data = JSON.parse(response.text || "{}");
  return data;
}

export async function generateFrameImage(prompt: string): Promise<string> {
  const ai = await getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          text: `Professional cinematic storyboard frame: ${prompt}. High quality, cinematic lighting, conceptual art style.`,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "16:9",
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the AI");
}

export async function generateVideo(imagePrompt: string, base64Image: string): Promise<string> {
  // Use the injectable API key for Veo
  const apiKey = process.env.API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('API Key missing');
  
  const ai = new GoogleGenAI({ apiKey });
  
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-lite-generate-preview',
    prompt: `Animate this cinematic storyboard frame: ${imagePrompt}`,
    image: {
      imageBytes: base64Image.split(',')[1], // Remove data:image/png;base64,
      mimeType: 'image/png',
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '16:9'
    }
  });

  // Poll for completion
  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 5000));
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (!downloadLink) throw new Error('Failed to get video download link');

  // Fetch the video data as a blob
  const response = await fetch(downloadLink, {
    method: 'GET',
    headers: {
      'x-goog-api-key': apiKey,
    },
  });

  if (!response.ok) throw new Error(`Failed to download video: ${response.statusText}`);
  
  const blob = await response.blob();
  return URL.createObjectURL(blob);
}
